### PR TITLE
Display QR-Code

### PR DESCRIPTION
**Pull request by jongbonga**
- #5

### CODE REVIEW

**Review by longtomjr — COMMENTED** [review]
Looks good. Happy to merge once the test issue have been resolved.

**Review by longtomjr — CHANGES_REQUESTED** [review]
We need to get the lock-file sorted before merging this

**Review by PiDelport — APPROVED** [review]
Cool, updated and looks good!

**Review by longtomjr — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
