### PR TITLE
Demo branch part 5

### PR DESCRIPTION
**Pull request by longtomjr**
We should pull out/refactor what is here into separate PRs so that we can have the flow implemented.

We also need to just go through the steps and go over the error handling where needed.

TODO:
- [x] Delay after confirming pin and loading screen displaying
- [x] Add text to the transaction loading screen that tells the user it will take a few seconds to be confirmed

TODO Refactor:
- [x] Refactor the wallet store, query, etc. to be called session store, query etc.
- [x] Merge/Refactor the `NewWalletService` and the `WalletService`. Not sure what separation will make the most sense in this context.

----

PR group:

- #111
- #112
- #113
- #114
- #71

### CODE REVIEW

**Comment by PiDelport** [comment]
Tests fixed! 🎉

**Comment by PiDelport** [comment]
(Rebase note: This didn't rebase easily with `--rebase-merges`, so I squashed the `wallet-access-cleanup` merge commit as a stepping stone.)

**Comment by PiDelport** [comment]
Cool, I did a  pass through this, and cleaned up and fixing things, and split the branch up into 5 smaller batches for easier review and merging.

**Review by longtomjr — COMMENTED** [review]
Happy to get this merged

**Review by jongbonga — APPROVED** [review]

**Comment by PiDelport** [comment]
@jongbonga: Cool, thanks for that fix! 🙏🏼

**Comment by PiDelport** [comment]
🎉

**Pull request merged**
