### PR TITLE
feat(web-client): add fontawesome

### PR DESCRIPTION
**Pull request by jongbonga**

### CODE REVIEW

**Review by longtomjr — APPROVED** [review]
Looks good.

**Comment by longtomjr** [comment]
@jongbonga Prettier check is failing, just check that on your end please

**Comment by jongbonga** [comment]
> @jongbonga Prettier check is failing, just check that on your end please

Yes, just pushed an update for that.

**Review by longtomjr — CHANGES_REQUESTED** [review]
For some reason there is a UI change in chromatic that is broken. Please have a look at that @jongbonga

**Review by longtomjr — APPROVED** [review]
Nevermind, the issue is the wrong baseline that were chosen by chromatic.  Will update the baseline there and then we can get this merged.

**Pull request merged**
